### PR TITLE
Fix byte array comparison

### LINKED ISSUE #10: Comparing zero length byte array fails
This currently fails:

```go
assert.Equal(t, []byte(""), []byte(nil))
```

Consider using [bytes.Equal](https://go.dev/play/), or special casing length zero.

### PR DESCRIPTION
**Pull request by sunesimonsen**
Fixes #10

### CODE REVIEW

**Comment by sunesimonsen** [comment]
@alecthomas is this something you are interesting in getting merged?

**Review by alecthomas — APPROVED** [review]

**Comment by alecthomas** [comment]
Sorry, I missed this! Awesome, thanks!

**Comment by sunesimonsen** [comment]
Wonderful - thanks <3

**Comment by sunesimonsen** [comment]
@alecthomas sorry if I'm being annoying, but could I also ask you to tag a new version 🙏

**Pull request merged**
